# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
stages:
  - build
  - deploy

job:
    stage: build
    image: python:3.11
    script:
        - pip install poetry
        - poetry install --with docs
    artifacts:
        untracked: true

pages:
  stage: deploy
  script:
    - pip install poetry
    - poetry run sphinx-build -b html docs docs/_build/html
    - mkdir .public
    - cp -r docs/_build/html/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
    - plot3d
  tags: [plot3d]
