name = "Plot3D"
uuid = "f5328629-7c59-4ce8-a074-6f660a963e40"
authors = ["paht.juangphanich@gmail.com"]
version = "1.0.0-DEV"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
